INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (3, 3, 1);
INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (6, 6, 1);
INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (4, 4, 1);
INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (1, 1, 1);
INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (2, 2, 1);
INSERT INTO "AVATAR_IMAGE" ("AVATAR_IMAGE_ID", "USER_ID", "AVATAR_IMAGE_IN_USE") VALUES (5, 5, 1);
