INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (3, 2);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (4, 1);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (6, 1);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (9, 1);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (11, 1);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (2, 1);
INSERT INTO "MESSAGE_IMAGE" ("MESSAGE_ID", "MESSAGE_IMAGE_COUNT") VALUES (18, 1);
