INSERT INTO "MESSAGE_OWNS_TOPIC" ("MESSAGE_ID", "TOPIC_ID") VALUES (2, 1);
INSERT INTO "MESSAGE_OWNS_TOPIC" ("MESSAGE_ID", "TOPIC_ID") VALUES (5, 2);
INSERT INTO "MESSAGE_OWNS_TOPIC" ("MESSAGE_ID", "TOPIC_ID") VALUES (19, 3);
