INSERT INTO "TOPIC" ("TOPIC_ID", "TOPIC_HEAT", "TOPIC_CONTENT") VALUES (2, 2, 'PUBG');
INSERT INTO "TOPIC" ("TOPIC_ID", "TOPIC_HEAT", "TOPIC_CONTENT") VALUES (1, 3, '宠物');
INSERT INTO "TOPIC" ("TOPIC_ID", "TOPIC_HEAT", "TOPIC_CONTENT") VALUES (3, 1, 'LOL');
