INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (1, '123456', 'Male', 'PlumLopez', '449136320@qq.com');
INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (2, '123456', 'Male', 'White Lu', 'white@qq.com');
INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (6, '123456', 'Male', 'Zihao Jian', 'uzi@qq.com');
INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (3, '123456', 'Male', 'Liu Mou', 'pdd@qq.com');
INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (5, '123456', 'Female', 'Shu''an Li', 'shuan@qq.com');
INSERT INTO "USER_PRIVATE_INFO" ("USER_ID", "USER_PASSWORD", "USER_GENDER", "USER_REAL_NAME", "USER_EMAIL") VALUES (4, '123456', 'Male', 'Yzc', 'yzc@tongji.edu.cn');
